// Mock data for demo mode — no real database involved

export const COMPANY = 'Nome da Empresa'

export const MOCK_CALLS = [
  {
    id: 'OS-001',
    date: '2026-07-10',
    contact_name: 'Carlos Alberto Souza',
    contact_phone: '(11) 98765-4321',
    origin: 'whatsapp',
    status: 'aprovado',
    notes: 'Vazamento na cozinha, urgente.',
    call_address: 'Rua das Flores, 142',
    call_city: 'São Paulo',
    call_neighborhood: 'Jardim Paulista',
    contact_cpf: '123.456.789-00',
    service_category: 'Hidráulica',
    os_number: 'OS-001',
    total_value: 850,
    payment_method: 'PIX',
    payment_status: 'pago',
    team: 'Equipe Alpha',
  },
  {
    id: 'OS-002',
    date: '2026-07-11',
    contact_name: 'Fernanda Lima',
    contact_phone: '(11) 91234-5678',
    origin: 'telefone',
    status: 'aprovado',
    notes: 'Instalação de chuveiro e registro.',
    call_address: 'Av. Paulista, 900',
    call_city: 'São Paulo',
    call_neighborhood: 'Bela Vista',
    contact_cpf: '987.654.321-00',
    service_category: 'Hidráulica',
    os_number: 'OS-002',
    total_value: 1200,
    payment_method: 'Cartão',
    payment_status: 'pago',
    team: 'Equipe Beta',
  },
  {
    id: 'OS-003',
    date: '2026-07-12',
    contact_name: 'Roberto Mendes',
    contact_phone: '(11) 97777-3333',
    origin: 'indicacao',
    status: 'aprovado',
    notes: 'Curto-circuito no quadro elétrico.',
    call_address: 'Rua Augusta, 320',
    call_city: 'São Paulo',
    call_neighborhood: 'Consolação',
    contact_cpf: '456.789.123-00',
    service_category: 'Elétrica',
    os_number: 'OS-003',
    total_value: 2300,
    payment_method: 'Dinheiro + PIX',
    payment_status: 'parcial',
    team: 'Equipe Alpha',
  },
  {
    id: 'OS-004',
    date: '2026-07-13',
    contact_name: 'Juliana Costa',
    contact_phone: '(11) 96666-2222',
    origin: 'whatsapp',
    status: 'agendado',
    notes: 'Verificar infiltração no banheiro.',
    call_address: 'Rua Oscar Freire, 55',
    call_city: 'São Paulo',
    call_neighborhood: 'Cerqueira César',
    contact_cpf: null,
    service_category: 'Hidráulica',
    os_number: null,
    total_value: null,
    payment_method: null,
    payment_status: null,
    team: null,
  },
  {
    id: 'OS-005',
    date: '2026-07-14',
    contact_name: 'Marcos Pereira',
    contact_phone: '(11) 95555-1111',
    origin: 'instagram',
    status: 'agendado',
    notes: 'Instalação de ar-condicionado split.',
    call_address: 'Alameda Santos, 700',
    call_city: 'São Paulo',
    call_neighborhood: 'Jardins',
    contact_cpf: null,
    service_category: 'Ar-condicionado',
    os_number: null,
    total_value: null,
    payment_method: null,
    payment_status: null,
    team: null,
  },
  {
    id: 'OS-006',
    date: '2026-07-08',
    contact_name: 'Patricia Alves',
    contact_phone: '(11) 94444-0000',
    origin: 'site',
    status: 'aprovado',
    notes: 'Troca de torneiras e sifão.',
    call_address: 'Rua Haddock Lobo, 180',
    call_city: 'São Paulo',
    call_neighborhood: 'Higienópolis',
    contact_cpf: '321.654.987-00',
    service_category: 'Hidráulica',
    os_number: 'OS-004',
    total_value: 650,
    payment_method: 'PIX',
    payment_status: 'pago',
    team: 'Equipe Beta',
  },
  {
    id: 'OS-007',
    date: '2026-07-07',
    contact_name: 'Eduardo Santos',
    contact_phone: '(11) 93333-9999',
    origin: 'whatsapp',
    status: 'aberto',
    notes: 'Orçamento para reforma do banheiro.',
    call_address: 'Rua Pamplona, 145',
    call_city: 'São Paulo',
    call_neighborhood: 'Itaim Bibi',
    contact_cpf: null,
    service_category: 'Reforma',
    os_number: null,
    total_value: null,
    payment_method: null,
    payment_status: null,
    team: null,
  },
]

export const MOCK_EXPENSES = [
  { id: 'e1', description: 'Combustível — julho',   category: 'combustivel', amount: 380,  status: 'pago',     due_date: '2026-07-05', type: 'fixo' },
  { id: 'e2', description: 'Material hidráulico',   category: 'material',    amount: 720,  status: 'pago',     due_date: '2026-07-08', type: 'avulso' },
  { id: 'e3', description: 'Salário técnico — jul', category: 'salario',     amount: 2800, status: 'pago',     due_date: '2026-07-01', type: 'fixo' },
  { id: 'e4', description: 'Aluguel escritório',    category: 'aluguel',     amount: 1500, status: 'pago',     due_date: '2026-07-05', type: 'fixo' },
  { id: 'e5', description: 'Alimentação equipe',    category: 'alimentacao', amount: 310,  status: 'pago',     due_date: '2026-07-10', type: 'avulso' },
  { id: 'e6', description: 'Material elétrico',     category: 'material',    amount: 450,  status: 'pendente', due_date: '2026-07-20', type: 'avulso' },
  { id: 'e7', description: 'Manutenção veículo',    category: 'manutencao',  amount: 600,  status: 'pendente', due_date: '2026-07-25', type: 'avulso' },
]

export const MOCK_ENTRADAS = [
  { id: 'c1', description: 'Recebimento OS-001 — Carlos Souza',    amount: 850,  status: 'pago',     due_date: '2026-07-10', entry_type: 'servico' },
  { id: 'c2', description: 'Recebimento OS-002 — Fernanda Lima',   amount: 1200, status: 'pago',     due_date: '2026-07-11', entry_type: 'servico' },
  { id: 'c3', description: 'Recebimento OS-004 — Patricia Alves',  amount: 650,  status: 'pago',     due_date: '2026-07-08', entry_type: 'servico' },
  { id: 'c4', description: 'Sinal OS-003 — Roberto Mendes',        amount: 1150, status: 'pago',     due_date: '2026-07-12', entry_type: 'servico' },
  { id: 'c5', description: 'Restante OS-003 — Roberto Mendes',     amount: 1150, status: 'pendente', due_date: '2026-07-20', entry_type: 'servico' },
]

export const MOCK_CLIENTS = [
  { id: 'cl1', name: 'Carlos Alberto Souza', phone: '(11) 98765-4321', city: 'São Paulo', neighborhood: 'Jardim Paulista', calls: 2 },
  { id: 'cl2', name: 'Fernanda Lima',        phone: '(11) 91234-5678', city: 'São Paulo', neighborhood: 'Bela Vista',      calls: 1 },
  { id: 'cl3', name: 'Roberto Mendes',       phone: '(11) 97777-3333', city: 'São Paulo', neighborhood: 'Consolação',      calls: 3 },
  { id: 'cl4', name: 'Patricia Alves',       phone: '(11) 94444-0000', city: 'São Paulo', neighborhood: 'Higienópolis',    calls: 1 },
]
